[32mINFO    [0m root:test_login.py:48 ********** Verifying Login test ***********
[1m[31mERROR   [0m root:test_login.py:71 ********* Login test is failed **********